osx_image: xcode7.3
language: objective-c
branches:
  only:
    - master
xcode_project: STEventSource.xcodeproj
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
matrix:
  include:
    - xcode_scheme: STEventSource-iOS
      xcode_sdk: iphonesimulator
    - xcode_scheme: STEventSource-iOS-Framework
      xcode_sdk: iphonesimulator
    - xcode_scheme: STEventSource-Mac
      xcode_sdk: macosx
    - xcode_scheme: STEventSource-Mac-Framework
      xcode_sdk: macosx
